import React from "react";
import "../App.css";

// post.tsx
export default function StudyData() {
  return [
    {
      studyId: 1,
      subjectName: "PY",
      cohort: {
        cohortId: 101,
        batch: 1,
        year: 2025,
        isFirstSemester: true,
        isActive: true,
        subjects: [
          {
            subjectId: 201,
            name: "Algebra",
            bookName: "Advanced Algebra",
            isBook: true,
            batch: 1,
            weeklyContents: [
              {
                weeklyContentId: 301,
                subjectName: "Algebra",
                content: "Introduction to Linear Equations",
                week: 1,
                startDate: "2025-02-16",
                endDate: "2025-02-22",
                startPage: 1,
                endPage: 20,
              },
            ],
          },
        ],
      },
      isBook: true,
      section: 101,
      studyMaster: "Alice",
      studyMembers: ["Bob", "Charlie", "David"],
    },
    {
      studyId: 2,
      subjectName: "PY",
      cohort: {
        cohortId: 102,
        batch: 1,
        year: 2025,
        isFirstSemester: true,
        isActive: true,
        subjects: [
          {
            subjectId: 202,
            name: "Mechanics",
            bookName: "Classical Mechanics",
            isBook: true,
            batch: 1,
            weeklyContents: [
              {
                weeklyContentId: 302,
                subjectName: "Mechanics",
                content: "Newton's Laws of Motion",
                week: 1,
                startDate: "2025-02-16",
                endDate: "2025-02-22",
                startPage: 10,
                endPage: 30,
              },
            ],
          },
        ],
      },
      isBook: true,
      section: 102,
      studyMaster: "Eve",
      studyMembers: ["Frank", "Grace", "Hank"],
    },
    {
      studyId: 3,
      subjectName: "ML",
      cohort: {
        cohortId: 103,
        batch: 2,
        year: 2025,
        isFirstSemester: false,
        isActive: true,
        subjects: [
          {
            subjectId: 203,
            name: "Organic Chemistry",
            bookName: "Principles of Organic Chemistry",
            isBook: true,
            batch: 2,
            weeklyContents: [
              {
                weeklyContentId: 303,
                subjectName: "Organic Chemistry",
                content: "Introduction to Hydrocarbons",
                week: 2,
                startDate: "2025-02-23",
                endDate: "2025-02-29",
                startPage: 5,
                endPage: 25,
              },
            ],
          },
        ],
      },
      isBook: true,
      section: 103,
      studyMaster: "George",
      studyMembers: ["Ivy", "Jack", "Kate"],
    },
    {
      studyId: 4,
      subjectName: "DL",
      cohort: {
        cohortId: 104,
        batch: 2,
        year: 2025,
        isFirstSemester: false,
        isActive: true,
        subjects: [
          {
            subjectId: 204,
            name: "Genetics",
            bookName: "Fundamentals of Genetics",
            isBook: true,
            batch: 2,
            weeklyContents: [
              {
                weeklyContentId: 304,
                subjectName: "Genetics",
                content: "Introduction to DNA and RNA",
                week: 3,
                startDate: "2025-03-01",
                endDate: "2025-03-07",
                startPage: 15,
                endPage: 35,
              },
            ],
          },
        ],
      },
      isBook: true,
      section: 104,
      studyMaster: "DA",
      studyMembers: ["Mike", "Nina", "Oscar"],
    },
    {
      studyId: 5,
      subjectName: "Computer Science",
      cohort: {
        cohortId: 105,
        batch: 3,
        year: 2025,
        isFirstSemester: true,
        isActive: true,
        subjects: [
          {
            subjectId: 205,
            name: "Data Structures",
            bookName: "Introduction to Data Structures",
            isBook: true,
            batch: 3,
            weeklyContents: [
              {
                weeklyContentId: 305,
                subjectName: "Data Structures",
                content: "Introduction to Arrays and Linked Lists",
                week: 1,
                startDate: "2025-02-16",
                endDate: "2025-02-22",
                startPage: 1,
                endPage: 20,
              },
            ],
          },
        ],
      },
      isBook: true,
      section: 105,
      studyMaster: "PY",
      studyMembers: ["Quincy", "Rachel", "Sam"],
    },
    {
      studyId: 6,
      subjectName: "Economics",
      cohort: {
        cohortId: 106,
        batch: 3,
        year: 2025,
        isFirstSemester: false,
        isActive: true,
        subjects: [
          {
            subjectId: 206,
            name: "Microeconomics",
            bookName: "Microeconomic Theory",
            isBook: true,
            batch: 3,
            weeklyContents: [
              {
                weeklyContentId: 306,
                subjectName: "Microeconomics",
                content: "Introduction to Supply and Demand",
                week: 2,
                startDate: "2025-02-23",
                endDate: "2025-02-29",
                startPage: 5,
                endPage: 25,
              },
            ],
          },
        ],
      },
      isBook: true,
      section: 106,
      studyMaster: "Tom",
      studyMembers: ["Uma", "Victor", "Wendy"],
    },
    {
      studyId: 7,
      subjectName: "PY",
      cohort: {
        cohortId: 107,
        batch: 4,
        year: 2025,
        isFirstSemester: true,
        isActive: true,
        subjects: [
          {
            subjectId: 207,
            name: "World History",
            bookName: "History of Civilizations",
            isBook: true,
            batch: 4,
            weeklyContents: [
              {
                weeklyContentId: 307,
                subjectName: "World History",
                content: "Ancient Civilizations Overview",
                week: 1,
                startDate: "2025-02-16",
                endDate: "2025-02-22",
                startPage: 1,
                endPage: 20,
              },
            ],
          },
        ],
      },
      isBook: true,
      section: 107,
      studyMaster: "Yvonne",
      studyMembers: ["Zach", "Alex", "Brian"],
    },
    {
      studyId: 8,
      subjectName: "ML",
      cohort: {
        cohortId: 108,
        batch: 4,
        year: 2025,
        isFirstSemester: false,
        isActive: true,
        subjects: [
          {
            subjectId: 208,
            name: "Ethics",
            bookName: "Introduction to Ethics",
            isBook: true,
            batch: 4,
            weeklyContents: [
              {
                weeklyContentId: 308,
                subjectName: "Ethics",
                content: "Overview of Ethical Theories",
                week: 2,
                startDate: "2025-02-23",
                endDate: "2025-02-29",
                startPage: 5,
                endPage: 25,
              },
            ],
          },
        ],
      },
      isBook: true,
      section: 108,
      studyMaster: "Carl",
      studyMembers: ["Diana", "Ethan", "Fiona"],
    },
    {
      studyId: 9,
      subjectName: "DL",
      cohort: {
        cohortId: 109,
        batch: 5,
        year: 2025,
        isFirstSemester: true,
        isActive: true,
        subjects: [
          {
            subjectId: 209,
            name: "Cognitive Psychology",
            bookName: "Cognitive Science",
            isBook: true,
            batch: 5,
            weeklyContents: [
              {
                weeklyContentId: 309,
                subjectName: "Cognitive Psychology",
                content: "Introduction to Human Memory",
                week: 1,
                startDate: "2025-02-16",
                endDate: "2025-02-22",
                startPage: 1,
                endPage: 20,
              },
            ],
          },
        ],
      },
      isBook: true,
      section: 109,
      studyMaster: "Gina",
      studyMembers: ["Harry", "Ian", "Judy"],
    },
  ];
}
