import React from "react";
import "../App.css";

// alexandria.tsx
export default function SubjectData() {
  return [
    {
      subjectId: 1,
      name: "PY",
      isBook: true,
      batch: 6,
      weeklyContents: [
        {
          weeklyContentId: 1,
          subjectName: "PY",
          content: "OT(스터디 방식,개발환경 설정)",
          week: 1,
          startDate: [2025, 3, 11],
          endDate: [2025, 3, 11],
        },
        {
          weeklyContentId: 2,
          subjectName: "PY",
          content:
            "01장 파이썬이란 무엇인가?02장 파이썬 프로그래밍의 기초, 자료형 -1",
          week: 2,
          startDate: [2025, 3, 18],
          endDate: [2025, 3, 18],
        },
        {
          weeklyContentId: 3,
          subjectName: "PY",
          content: "02장 파이썬 프로그래밍의 기초, 자료형 - 2",
          week: 3,
          startDate: [2025, 3, 25],
          endDate: [2025, 3, 25],
        },
        {
          weeklyContentId: 4,
          subjectName: "PY",
          content: "02장 파이썬 프로그래밍의 기초, 자료형 - 2",
          week: 4,
          startDate: [2025, 3, 25],
          endDate: [2025, 3, 25],
        },
        {
          weeklyContentId: 5,
          subjectName: "PY",
          content: "02장 파이썬 프로그래밍의 기초, 자료형 - 2",
          week: 5,
          startDate: [2025, 3, 25],
          endDate: [2025, 3, 25],
        },
        {
          weeklyContentId: 6,
          subjectName: "PY",
          content: "02장 파이썬 프로그래밍의 기초, 자료형 - 2",
          week: 6,
          startDate: [2025, 3, 25],
          endDate: [2025, 3, 25],
        },
        {
          weeklyContentId: 7,
          subjectName: "PY",
          content: "02장 파이썬 프로그래밍의 기초, 자료형 - 2",
          week: 7,
          startDate: [2025, 3, 25],
          endDate: [2025, 3, 25],
        },
        {
          weeklyContentId: 8,
          subjectName: "PY",
          content: "02장 파이썬 프로그래밍의 기초, 자료형 - 2",
          week: 8,
          startDate: [2025, 3, 25],
          endDate: [2025, 3, 25],
        },
        {
          weeklyContentId: 9,
          subjectName: "PY",
          content: "02장 파이썬 프로그래밍의 기초, 자료형 - 2",
          week: 9,
          startDate: [2025, 3, 25],
          endDate: [2025, 3, 25],
        },
      ],
    },
    {
      subjectId: 1,
      name: "DA",
      isBook: true,
      batch: 6,
      weeklyContents: [
        {
          weeklyContentId: 1,
          subjectName: "PY",
          content: "OT(스터디 방식,개발환경 설정)",
          week: 1,
          startDate: [2025, 3, 11],
          endDate: [2025, 3, 11],
        },
        {
          weeklyContentId: 2,
          subjectName: "PY",
          content:
            "01장 파이썬이란 무엇인가?02장 파이썬 프로그래밍의 기초, 자료형 -1",
          week: 2,
          startDate: [2025, 3, 18],
          endDate: [2025, 3, 18],
        },
        {
          weeklyContentId: 3,
          subjectName: "PY",
          content: "02장 파이썬 프로그래밍의 기초, 자료형 - 2",
          week: 3,
          startDate: [2025, 3, 25],
          endDate: [2025, 3, 25],
        },
      ],
    },
    {
      subjectId: 1,
      name: "ML",
      isBook: true,
      batch: 6,
      weeklyContents: [
        {
          weeklyContentId: 1,
          subjectName: "PY",
          content: "OT(스터디 방식,개발환경 설정)",
          week: 1,
          startDate: [2025, 3, 11],
          endDate: [2025, 3, 11],
        },
        {
          weeklyContentId: 2,
          subjectName: "PY",
          content:
            "01장 파이썬이란 무엇인가?02장 파이썬 프로그래밍의 기초, 자료형 -1",
          week: 2,
          startDate: [2025, 3, 18],
          endDate: [2025, 3, 18],
        },
        {
          weeklyContentId: 3,
          subjectName: "PY",
          content: "02장 파이썬 프로그래밍의 기초, 자료형 - 2",
          week: 3,
          startDate: [2025, 3, 25],
          endDate: [2025, 3, 25],
        },
        {
          weeklyContentId: 1,
          subjectName: "PY",
          content: "OT(스터디 방식,개발환경 설정)",
          week: 1,
          startDate: [2025, 3, 11],
          endDate: [2025, 3, 11],
        },
        {
          weeklyContentId: 2,
          subjectName: "PY",
          content:
            "01장 파이썬이란 무엇인가?02장 파이썬 프로그래밍의 기초, 자료형 -1",
          week: 2,
          startDate: [2025, 3, 18],
          endDate: [2025, 3, 18],
        },
        {
          weeklyContentId: 3,
          subjectName: "PY",
          content: "02장 파이썬 프로그래밍의 기초, 자료형 - 2",
          week: 3,
          startDate: [2025, 3, 25],
          endDate: [2025, 3, 25],
        },
        {
          weeklyContentId: 1,
          subjectName: "PY",
          content: "OT(스터디 방식,개발환경 설정)",
          week: 1,
          startDate: [2025, 3, 11],
          endDate: [2025, 3, 11],
        },
        {
          weeklyContentId: 2,
          subjectName: "PY",
          content:
            "01장 파이썬이란 무엇인가?02장 파이썬 프로그래밍의 기초, 자료형 -1",
          week: 2,
          startDate: [2025, 3, 18],
          endDate: [2025, 3, 18],
        },
        {
          weeklyContentId: 3,
          subjectName: "PY",
          content: "02장 파이썬 프로그래밍의 기초, 자료형 - 2",
          week: 3,
          startDate: [2025, 3, 25],
          endDate: [2025, 3, 25],
        },
      ],
    },
    {
      subjectId: 1,
      name: "DL",
      isBook: true,
      batch: 6,
      weeklyContents: [
        {
          weeklyContentId: 1,
          subjectName: "PY",
          content: "OT(스터디 방식,개발환경 설정)",
          week: 1,
          startDate: [2025, 3, 11],
          endDate: [2025, 3, 11],
        },
        {
          weeklyContentId: 2,
          subjectName: "PY",
          content:
            "01장 파이썬이란 무엇인가?02장 파이썬 프로그래밍의 기초, 자료형 -1",
          week: 2,
          startDate: [2025, 3, 18],
          endDate: [2025, 3, 18],
        },
        {
          weeklyContentId: 3,
          subjectName: "PY",
          content: "02장 파이썬 프로그래밍의 기초, 자료형 - 2",
          week: 3,
          startDate: [2025, 3, 25],
          endDate: [2025, 3, 25],
        },
        {
          weeklyContentId: 1,
          subjectName: "PY",
          content: "OT(스터디 방식,개발환경 설정)",
          week: 1,
          startDate: [2025, 3, 11],
          endDate: [2025, 3, 11],
        },
        {
          weeklyContentId: 2,
          subjectName: "PY",
          content:
            "01장 파이썬이란 무엇인가?02장 파이썬 프로그래밍의 기초, 자료형 -1",
          week: 2,
          startDate: [2025, 3, 18],
          endDate: [2025, 3, 18],
        },
        {
          weeklyContentId: 3,
          subjectName: "PY",
          content: "02장 파이썬 프로그래밍의 기초, 자료형 - 2",
          week: 3,
          startDate: [2025, 3, 25],
          endDate: [2025, 3, 25],
        },
        {
          weeklyContentId: 1,
          subjectName: "PY",
          content: "OT(스터디 방식,개발환경 설정)",
          week: 1,
          startDate: [2025, 3, 11],
          endDate: [2025, 3, 11],
        },
        {
          weeklyContentId: 2,
          subjectName: "PY",
          content:
            "01장 파이썬이란 무엇인가?02장 파이썬 프로그래밍의 기초, 자료형 -1",
          week: 2,
          startDate: [2025, 3, 18],
          endDate: [2025, 3, 18],
        },
        {
          weeklyContentId: 3,
          subjectName: "PY",
          content: "02장 파이썬 프로그래밍의 기초, 자료형 - 2",
          week: 3,
          startDate: [2025, 3, 25],
          endDate: [2025, 3, 25],
        },
      ],
    },
  ];
}
